- name: set app_data
  set_fact:
    app_data: "{{ applications[k8s_namespace.key][application.key] }}"

- name: .{{ name_prefix }} files
  debug:
    msg: "key: {{ file.key }} val:{{ file.value }}"

- name: .{{ name_prefix }} tempfile for {{ file.key }}
  tempfile:
    state: file
  register: tmp_file

- debug:
    var: net.routes

- name: .{{ name_prefix }} copy template to tempfile
  template:
    src: "{{ file.value.file }}"
    dest: "{{ tmp_file.path }}"

