---
- name: rc.conf
  lineinfile:
    path: /etc/rc.conf
    regexp: "^{{ item.setting }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.setting }}"
    backup: yes
  loop:
    - line: 'rc_cgroup_mode="unified"'
      setting: rc_cgroup_mode
    - line: 'rc_cgroup_controllers=""'
      setting: rc_cgroup_controllers

- name: deploy configuration files
  copy:
    src: "{{ item }}"
    dest: "/{{ item }}"
    mode: 0644
  loop:
    - etc/sysctl.d/k8s.conf
    - etc/modules-load.d/k8s.conf
    - etc/conf.d/kubelet
    - etc/kubernetes/kubeadm.conf
    - etc/kubernetes/audit-policy.yaml 
    - etc/kubernetes/AdmissionConfiguration.yaml

- name: check /var/lib/etcd
  stat:
    path: "/var/lib/etcd"
  register: etcd_data

- name: ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    mode: "{{ item.perm }}"
  loop:
  - path: /data/etcd
    perm: u=rwx,g=rx,o=rx
  - path: "{{ k8s_log_directory }}"
    perm: u=rwx,g=rx,o=rx

- name: ensure /var/lib/etcd is absent
  file:
    path: /var/lib/etcd
    state: absent
  when: not ( etcd_data.stat.islnk is defined and etcd_data.stat.islnk)

- name: create /var/lib/etcd link to /data/etcd
  file:
    src: "/data/etcd"
    dest: "/var/lib/etcd"
    owner: root
    group: root
    state: link
  when: not ( etcd_data.stat.islnk is defined and etcd_data.stat.islnk)

- name: Create sparse disk image file
  command:
    cmd: "truncate -s {{ longhorn_size }} {{ longhorn_disk }}"
    creates: "{{ longhorn_disk }}" # Only runs if file doesn't exist

- name: Format the disk image with ext4
  community.general.filesystem:
    fstype: ext4
    dev: "{{ longhorn_disk }}"

- name: Create auto.longhorn map file
  copy:
    dest: /etc/autofs/auto.longhorn
    content: |
      /var/lib/longhorn -fstype=auto,loop,shared,noatime :{{ longhorn_disk }}
  notify: restart autofs

- name: ensure Longhorn direct map is in auto.master
  lineinfile:
    path: /etc/autofs/auto.master
    regexp: '^/-\s+/etc/autofs/auto\.longhorn'
    line: "/- /etc/autofs/auto.longhorn --timeout=0"
    state: present
