config:
  cookieSecret: "2I7BWFfNiFuBQdh4tEaFyuT8KnaPtNMMGLzP-uoG3YU=" # https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview/#generating-a-cookie-secret
  # cookieName: "_oauth2_proxy"    # Name of the cookie that oauth2-proxy creates, if not set defaults to "_oauth2_proxy"
  ssl_insecure_skip_verify: true
  configFile: |-
        email_domains = [ "*" ]        # Restrict to these E-Mail Domains, a wildcard "*" allows any email
        cookie_secret = "2I7BWFfNiFuBQdh4tEaFyuT8KnaPtNMMGLzP-uoG3YU="
        ssl_insecure_skip_verify = true
alphaConfig:
  enabled: true
  configData:
    providers:
    - clientID: "test"       # IdP Client ID
      clientSecret: "oyoEa5qajmOqBFtJHWEg2iZhGli5nQu0"   # IdP Client Secret
      id: oidc-istio
      provider: oidc   # We use the generic 'oidc' provider
      #loginURL: https://my-lb.adm13:2005/realms/test/protocol/openid-connect/auth
      loginURL: https://keycloak.my-lb.adm13/realms/test/protocol/openid-connect/auth
      redeemURL: http://keycloak.auth:1121/realms/test/protocol/openid-connect/token
      profileURL: http://keycloak.auth:1121/realms/test/protocol/openid-connect/userinfo
      validateURL: http://keycloak.auth:1121/realms/test/protocol/openid-connect/userinfo
      scope: "openid"
      # scope: "openid email profile groups"
#      allowedGroups:
#      - admins # List all groups managed at our your IdP which should be allowed access
#      - test
    # - infrateam
    # - anothergroup
      oidcConfig:
        userIDClaim: email  # Name of the claim in JWT containing the User ID
        #emailClaim: email.  # Name of the clain in JWT containing the E-Mail
        emailClaim: email  # Name of the clain in JWT containing the E-Mail
        groupsClaim: groups # Name of the claim in JWT containing the Groups
        extraAudiences: 
        - test
        audienceClaims:
        - aud
        skipDiscovery: true # You can try using the well-knwon endpoint directly for auto discovery, here we won't use it
        # issuerURL: https://my-lb.adm13:2005/realms/test
        issuerURL: https://keycloak.my-lb.adm13/realms/test
        jwksURL: http://keycloak.auth:1121/realms/test/protocol/openid-connect/certs
    upstreamConfig:
      upstreams:
        - id: static_200
          path: /
          static: true
          staticCode: 200
    # Headers that should be added to responses from the proxy
    injectResponseHeaders: # Send this headers in responses from oauth2-proxy
      - name: X-Auth-Request-Preferred-Username
        values:
          - claim: preferred_username
      - name: X-Auth-Request-Email
        values:
          - claim: email
extraArgs:
  cookie-secure: "false"
  cookie-domain: "my-lb.adm13"   # Replace with your base domain
  cookie-samesite: lax
  cookie-expire: 12h               # How long our Cookie is valid
  auth-logging: true               # Enable / Disable auth logs
  request-logging: true            # Enable / Disable request logs
  standard-logging: true           # Enable / Disable the standart logs
  show-debug-on-error: true        # Disable in production setups
  skip-provider-button: true       # We only have one provider configured (Keycloak)
  silence-ping-logging: true       # Keeps our logs clean
  whitelist-domain: "my-lb.adm13" # Replace with your base domain

