kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: cgroupfs
---
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
localAPIEndpoint:
  advertiseAddress: {{ internal_first_master_ip | default("0.0.0.0")  }}

---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
imageRepository: "{{ registry }}/k8s"
controlPlaneEndpoint: "{{ controlPlaneEndpoint }}"
networking:
 podSubnet: "{{ k8s.podSubnet }}"
kubernetesVersion: "{{ k8s_version }}"
---
kind: JoinConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
controlPlane:
  localAPIEndpoint:
    advertiseAddress: {{ join_ip | default("0.0.0.0") }}
  certificateKey: {{ cert_key | default("I have none") }}
discovery:
  bootstrapToken:
    token: "{{ token }}"
    apiServerEndpoint: "{{ controlPlaneEndpoint }}"
    caCertHashes:
    - "{{ discovery_token_ca_cert_hash }}"
